hico_verb_object_list = [('board', 'airplane'),
 ('direct', 'airplane'),
 ('exit', 'airplane'),
 ('fly', 'airplane'),
 ('inspect', 'airplane'),
 ('load', 'airplane'),
 ('ride', 'airplane'),
 ('sit on', 'airplane'),
 ('wash', 'airplane'),
 ('no interaction', 'airplane'),
 ('carry', 'bicycle'),
 ('hold', 'bicycle'),
 ('inspect', 'bicycle'),
 ('jump', 'bicycle'),
 ('hop on', 'bicycle'),
 ('park', 'bicycle'),
 ('push', 'bicycle'),
 ('repair', 'bicycle'),
 ('ride', 'bicycle'),
 ('sit on', 'bicycle'),
 ('straddle', 'bicycle'),
 ('walk', 'bicycle'),
 ('wash', 'bicycle'),
 ('no interaction', 'bicycle'),
 ('chase', 'bird'),
 ('feed', 'bird'),
 ('hold', 'bird'),
 ('pet', 'bird'),
 ('release', 'bird'),
 ('watch', 'bird'),
 ('no interaction', 'bird'),
 ('board', 'boat'),
 ('drive', 'boat'),
 ('exit', 'boat'),
 ('inspect', 'boat'),
 ('jump', 'boat'),
 ('launch', 'boat'),
 ('repair', 'boat'),
 ('ride', 'boat'),
 ('row', 'boat'),
 ('sail', 'boat'),
 ('sit on', 'boat'),
 ('stand on', 'boat'),
 ('tie', 'boat'),
 ('wash', 'boat'),
 ('no interaction', 'boat'),
 ('carry', 'bottle'),
 ('drink with', 'bottle'),
 ('hold', 'bottle'),
 ('inspect', 'bottle'),
 ('lick', 'bottle'),
 ('open', 'bottle'),
 ('pour', 'bottle'),
 ('no interaction', 'bottle'),
 ('board', 'bus'),
 ('direct', 'bus'),
 ('drive', 'bus'),
 ('exit', 'bus'),
 ('inspect', 'bus'),
 ('load', 'bus'),
 ('ride', 'bus'),
 ('sit on', 'bus'),
 ('wash', 'bus'),
 ('wave', 'bus'),
 ('no interaction', 'bus'),
 ('board', 'car'),
 ('direct', 'car'),
 ('drive', 'car'),
 ('hose', 'car'),
 ('inspect', 'car'),
 ('jump', 'car'),
 ('load', 'car'),
 ('park', 'car'),
 ('ride', 'car'),
 ('wash', 'car'),
 ('no interaction', 'car'),
 ('dry', 'cat'),
 ('feed', 'cat'),
 ('hold', 'cat'),
 ('hug', 'cat'),
 ('kiss', 'cat'),
 ('pet', 'cat'),
 ('scratch', 'cat'),
 ('wash', 'cat'),
 ('chase', 'cat'),
 ('no interaction', 'cat'),
 ('carry', 'chair'),
 ('hold', 'chair'),
 ('lie on', 'chair'),
 ('sit on', 'chair'),
 ('stand on', 'chair'),
 ('no interaction', 'chair'),
 ('carry', 'couch'),
 ('lie on', 'couch'),
 ('sit on', 'couch'),
 ('no interaction', 'couch'),
 ('feed', 'cow'),
 ('herd', 'cow'),
 ('hold', 'cow'),
 ('hug', 'cow'),
 ('kiss', 'cow'),
 ('lasso', 'cow'),
 ('milk', 'cow'),
 ('pet', 'cow'),
 ('ride', 'cow'),
 ('walk', 'cow'),
 ('no interaction', 'cow'),
 ('clean', 'dining table'),
 ('eat at', 'dining table'),
 ('sit at', 'dining table'),
 ('no interaction', 'dining table'),
 ('carry', 'dog'),
 ('dry', 'dog'),
 ('feed', 'dog'),
 ('groom', 'dog'),
 ('hold', 'dog'),
 ('hose', 'dog'),
 ('hug', 'dog'),
 ('inspect', 'dog'),
 ('kiss', 'dog'),
 ('pet', 'dog'),
 ('run', 'dog'),
 ('scratch', 'dog'),
 ('straddle', 'dog'),
 ('train', 'dog'),
 ('walk', 'dog'),
 ('wash', 'dog'),
 ('chase', 'dog'),
 ('no interaction', 'dog'),
 ('feed', 'horse'),
 ('groom', 'horse'),
 ('hold', 'horse'),
 ('hug', 'horse'),
 ('jump', 'horse'),
 ('kiss', 'horse'),
 ('load', 'horse'),
 ('hop on', 'horse'),
 ('pet', 'horse'),
 ('race', 'horse'),
 ('ride', 'horse'),
 ('run', 'horse'),
 ('straddle', 'horse'),
 ('train', 'horse'),
 ('walk', 'horse'),
 ('wash', 'horse'),
 ('no interaction', 'horse'),
 ('hold', 'motorcycle'),
 ('inspect', 'motorcycle'),
 ('jump', 'motorcycle'),
 ('hop on', 'motorcycle'),
 ('park', 'motorcycle'),
 ('push', 'motorcycle'),
 ('race', 'motorcycle'),
 ('ride', 'motorcycle'),
 ('sit on', 'motorcycle'),
 ('straddle', 'motorcycle'),
 ('turn', 'motorcycle'),
 ('walk', 'motorcycle'),
 ('wash', 'motorcycle'),
 ('no interaction', 'motorcycle'),
 ('carry', 'person'),
 ('greet', 'person'),
 ('hold', 'person'),
 ('hug', 'person'),
 ('kiss', 'person'),
 ('stab', 'person'),
 ('tag', 'person'),
 ('teach', 'person'),
 ('lick', 'person'),
 ('no interaction', 'person'),
 ('carry', 'potted plant'),
 ('hold', 'potted plant'),
 ('hose', 'potted plant'),
 ('no interaction', 'potted plant'),
 ('carry', 'sheep'),
 ('feed', 'sheep'),
 ('herd', 'sheep'),
 ('hold', 'sheep'),
 ('hug', 'sheep'),
 ('kiss', 'sheep'),
 ('pet', 'sheep'),
 ('ride', 'sheep'),
 ('shear', 'sheep'),
 ('walk', 'sheep'),
 ('wash', 'sheep'),
 ('no interaction', 'sheep'),
 ('board', 'train'),
 ('drive', 'train'),
 ('exit', 'train'),
 ('load', 'train'),
 ('ride', 'train'),
 ('sit on', 'train'),
 ('wash', 'train'),
 ('no interaction', 'train'),
 ('control', 'tv'),
 ('repair', 'tv'),
 ('watch', 'tv'),
 ('no interaction', 'tv'),
 ('buy', 'apple'),
 ('cut', 'apple'),
 ('eat', 'apple'),
 ('hold', 'apple'),
 ('inspect', 'apple'),
 ('peel', 'apple'),
 ('pick', 'apple'),
 ('smell', 'apple'),
 ('wash', 'apple'),
 ('no interaction', 'apple'),
 ('carry', 'backpack'),
 ('hold', 'backpack'),
 ('inspect', 'backpack'),
 ('open', 'backpack'),
 ('wear', 'backpack'),
 ('no interaction', 'backpack'),
 ('buy', 'banana'),
 ('carry', 'banana'),
 ('cut', 'banana'),
 ('eat', 'banana'),
 ('hold', 'banana'),
 ('inspect', 'banana'),
 ('peel', 'banana'),
 ('pick', 'banana'),
 ('smell', 'banana'),
 ('no interaction', 'banana'),
 ('break', 'baseball bat'),
 ('carry', 'baseball bat'),
 ('hold', 'baseball bat'),
 ('sign', 'baseball bat'),
 ('swing', 'baseball bat'),
 ('throw', 'baseball bat'),
 ('wield', 'baseball bat'),
 ('no interaction', 'baseball bat'),
 ('hold', 'baseball glove'),
 ('wear', 'baseball glove'),
 ('no interaction', 'baseball glove'),
 ('feed', 'bear'),
 ('hunt', 'bear'),
 ('watch', 'bear'),
 ('no interaction', 'bear'),
 ('clean', 'bed'),
 ('lie on', 'bed'),
 ('sit on', 'bed'),
 ('no interaction', 'bed'),
 ('inspect', 'bench'),
 ('lie on', 'bench'),
 ('sit on', 'bench'),
 ('no interaction', 'bench'),
 ('carry', 'book'),
 ('hold', 'book'),
 ('open', 'book'),
 ('read', 'book'),
 ('no interaction', 'book'),
 ('hold', 'bowl'),
 ('stir', 'bowl'),
 ('wash', 'bowl'),
 ('lick', 'bowl'),
 ('no interaction', 'bowl'),
 ('cut', 'broccoli'),
 ('eat', 'broccoli'),
 ('hold', 'broccoli'),
 ('smell', 'broccoli'),
 ('stir', 'broccoli'),
 ('wash', 'broccoli'),
 ('no interaction', 'broccoli'),
 ('blow', 'cake'),
 ('carry', 'cake'),
 ('cut', 'cake'),
 ('eat', 'cake'),
 ('hold', 'cake'),
 ('light', 'cake'),
 ('make', 'cake'),
 ('pick up', 'cake'),
 ('no interaction', 'cake'),
 ('carry', 'carrot'),
 ('cook', 'carrot'),
 ('cut', 'carrot'),
 ('eat', 'carrot'),
 ('hold', 'carrot'),
 ('peel', 'carrot'),
 ('smell', 'carrot'),
 ('stir', 'carrot'),
 ('wash', 'carrot'),
 ('no interaction', 'carrot'),
 ('carry', 'cell phone'),
 ('hold', 'cell phone'),
 ('read', 'cell phone'),
 ('repair', 'cell phone'),
 ('talk on', 'cell phone'),
 ('text on', 'cell phone'),
 ('no interaction', 'cell phone'),
 ('check', 'clock'),
 ('hold', 'clock'),
 ('repair', 'clock'),
 ('set', 'clock'),
 ('no interaction', 'clock'),
 ('carry', 'cup'),
 ('drink with', 'cup'),
 ('hold', 'cup'),
 ('inspect', 'cup'),
 ('pour', 'cup'),
 ('sip', 'cup'),
 ('smell', 'cup'),
 ('fill', 'cup'),
 ('wash', 'cup'),
 ('no interaction', 'cup'),
 ('buy', 'donut'),
 ('carry', 'donut'),
 ('eat', 'donut'),
 ('hold', 'donut'),
 ('make', 'donut'),
 ('pick up', 'donut'),
 ('smell', 'donut'),
 ('no interaction', 'donut'),
 ('feed', 'elephant'),
 ('hold', 'elephant'),
 ('hose', 'elephant'),
 ('hug', 'elephant'),
 ('kiss', 'elephant'),
 ('hop on', 'elephant'),
 ('pet', 'elephant'),
 ('ride', 'elephant'),
 ('walk', 'elephant'),
 ('wash', 'elephant'),
 ('watch', 'elephant'),
 ('no interaction', 'elephant'),
 ('hug', 'fire hydrant'),
 ('inspect', 'fire hydrant'),
 ('open', 'fire hydrant'),
 ('paint', 'fire hydrant'),
 ('no interaction', 'fire hydrant'),
 ('hold', 'fork'),
 ('lift', 'fork'),
 ('stick', 'fork'),
 ('lick', 'fork'),
 ('wash', 'fork'),
 ('no interaction', 'fork'),
 ('block', 'frisbee'),
 ('catch', 'frisbee'),
 ('hold', 'frisbee'),
 ('spin', 'frisbee'),
 ('throw', 'frisbee'),
 ('no interaction', 'frisbee'),
 ('feed', 'giraffe'),
 ('kiss', 'giraffe'),
 ('pet', 'giraffe'),
 ('ride', 'giraffe'),
 ('watch', 'giraffe'),
 ('no interaction', 'giraffe'),
 ('hold', 'hair drier'),
 ('operate', 'hair drier'),
 ('repair', 'hair drier'),
 ('no interaction', 'hair drier'),
 ('carry', 'handbag'),
 ('hold', 'handbag'),
 ('inspect', 'handbag'),
 ('no interaction', 'handbag'),
 ('carry', 'hot dog'),
 ('cook', 'hot dog'),
 ('cut', 'hot dog'),
 ('eat', 'hot dog'),
 ('hold', 'hot dog'),
 ('make', 'hot dog'),
 ('no interaction', 'hot dog'),
 ('carry', 'keyboard'),
 ('clean', 'keyboard'),
 ('hold', 'keyboard'),
 ('type on', 'keyboard'),
 ('no interaction', 'keyboard'),
 ('assemble', 'kite'),
 ('carry', 'kite'),
 ('fly', 'kite'),
 ('hold', 'kite'),
 ('inspect', 'kite'),
 ('launch', 'kite'),
 ('pull', 'kite'),
 ('no interaction', 'kite'),
 ('cut with', 'knife'),
 ('hold', 'knife'),
 ('stick', 'knife'),
 ('wash', 'knife'),
 ('wield', 'knife'),
 ('lick', 'knife'),
 ('no interaction', 'knife'),
 ('hold', 'laptop'),
 ('open', 'laptop'),
 ('read', 'laptop'),
 ('repair', 'laptop'),
 ('type on', 'laptop'),
 ('no interaction', 'laptop'),
 ('clean', 'microwave'),
 ('open', 'microwave'),
 ('operate', 'microwave'),
 ('no interaction', 'microwave'),
 ('control', 'mouse'),
 ('hold', 'mouse'),
 ('repair', 'mouse'),
 ('no interaction', 'mouse'),
 ('buy', 'orange'),
 ('cut', 'orange'),
 ('eat', 'orange'),
 ('hold', 'orange'),
 ('inspect', 'orange'),
 ('peel', 'orange'),
 ('pick', 'orange'),
 ('squeeze', 'orange'),
 ('wash', 'orange'),
 ('no interaction', 'orange'),
 ('clean', 'oven'),
 ('hold', 'oven'),
 ('inspect', 'oven'),
 ('open', 'oven'),
 ('repair', 'oven'),
 ('operate', 'oven'),
 ('no interaction', 'oven'),
 ('check', 'parking meter'),
 ('pay', 'parking meter'),
 ('repair', 'parking meter'),
 ('no interaction', 'parking meter'),
 ('buy', 'pizza'),
 ('carry', 'pizza'),
 ('cook', 'pizza'),
 ('cut', 'pizza'),
 ('eat', 'pizza'),
 ('hold', 'pizza'),
 ('make', 'pizza'),
 ('pick up', 'pizza'),
 ('slide', 'pizza'),
 ('smell', 'pizza'),
 ('no interaction', 'pizza'),
 ('clean', 'refrigerator'),
 ('hold', 'refrigerator'),
 ('move', 'refrigerator'),
 ('open', 'refrigerator'),
 ('no interaction', 'refrigerator'),
 ('hold', 'remote'),
 ('point', 'remote'),
 ('swing', 'remote'),
 ('no interaction', 'remote'),
 ('carry', 'sandwich'),
 ('cook', 'sandwich'),
 ('cut', 'sandwich'),
 ('eat', 'sandwich'),
 ('hold', 'sandwich'),
 ('make', 'sandwich'),
 ('no interaction', 'sandwich'),
 ('cut with', 'scissors'),
 ('hold', 'scissors'),
 ('open', 'scissors'),
 ('no interaction', 'scissors'),
 ('clean', 'sink'),
 ('repair', 'sink'),
 ('wash', 'sink'),
 ('no interaction', 'sink'),
 ('carry', 'skateboard'),
 ('flip', 'skateboard'),
 ('grind', 'skateboard'),
 ('hold', 'skateboard'),
 ('jump', 'skateboard'),
 ('pick up', 'skateboard'),
 ('ride', 'skateboard'),
 ('sit on', 'skateboard'),
 ('stand on', 'skateboard'),
 ('no interaction', 'skateboard'),
 ('adjust', 'skis'),
 ('carry', 'skis'),
 ('hold', 'skis'),
 ('inspect', 'skis'),
 ('jump', 'skis'),
 ('pick up', 'skis'),
 ('repair', 'skis'),
 ('ride', 'skis'),
 ('stand on', 'skis'),
 ('wear', 'skis'),
 ('no interaction', 'skis'),
 ('adjust', 'snowboard'),
 ('carry', 'snowboard'),
 ('grind', 'snowboard'),
 ('hold', 'snowboard'),
 ('jump', 'snowboard'),
 ('ride', 'snowboard'),
 ('stand on', 'snowboard'),
 ('wear', 'snowboard'),
 ('no interaction', 'snowboard'),
 ('hold', 'spoon'),
 ('lick', 'spoon'),
 ('wash', 'spoon'),
 ('sip', 'spoon'),
 ('no interaction', 'spoon'),
 ('block', 'sports ball'),
 ('carry', 'sports ball'),
 ('catch', 'sports ball'),
 ('dribble', 'sports ball'),
 ('hit', 'sports ball'),
 ('hold', 'sports ball'),
 ('inspect', 'sports ball'),
 ('kick', 'sports ball'),
 ('pick up', 'sports ball'),
 ('serve', 'sports ball'),
 ('sign', 'sports ball'),
 ('spin', 'sports ball'),
 ('throw', 'sports ball'),
 ('no interaction', 'sports ball'),
 ('hold', 'stop sign'),
 ('stand under', 'stop sign'),
 ('stop at', 'stop sign'),
 ('no interaction', 'stop sign'),
 ('carry', 'suitcase'),
 ('drag', 'suitcase'),
 ('hold', 'suitcase'),
 ('hug', 'suitcase'),
 ('load', 'suitcase'),
 ('open', 'suitcase'),
 ('pack', 'suitcase'),
 ('pick up', 'suitcase'),
 ('zip', 'suitcase'),
 ('no interaction', 'suitcase'),
 ('carry', 'surfboard'),
 ('drag', 'surfboard'),
 ('hold', 'surfboard'),
 ('inspect', 'surfboard'),
 ('jump', 'surfboard'),
 ('lie on', 'surfboard'),
 ('load', 'surfboard'),
 ('ride', 'surfboard'),
 ('stand on', 'surfboard'),
 ('sit on', 'surfboard'),
 ('wash', 'surfboard'),
 ('no interaction', 'surfboard'),
 ('carry', 'teddy bear'),
 ('hold', 'teddy bear'),
 ('hug', 'teddy bear'),
 ('kiss', 'teddy bear'),
 ('no interaction', 'teddy bear'),
 ('carry', 'tennis racket'),
 ('hold', 'tennis racket'),
 ('inspect', 'tennis racket'),
 ('swing', 'tennis racket'),
 ('no interaction', 'tennis racket'),
 ('adjust', 'tie'),
 ('cut', 'tie'),
 ('hold', 'tie'),
 ('inspect', 'tie'),
 ('pull', 'tie'),
 ('tie', 'tie'),
 ('wear', 'tie'),
 ('no interaction', 'tie'),
 ('hold', 'toaster'),
 ('operate', 'toaster'),
 ('repair', 'toaster'),
 ('no interaction', 'toaster'),
 ('clean', 'toilet'),
 ('flush', 'toilet'),
 ('open', 'toilet'),
 ('repair', 'toilet'),
 ('sit on', 'toilet'),
 ('stand on', 'toilet'),
 ('wash', 'toilet'),
 ('no interaction', 'toilet'),
 ('brush with', 'toothbrush'),
 ('hold', 'toothbrush'),
 ('wash', 'toothbrush'),
 ('no interaction', 'toothbrush'),
 ('install', 'traffic light'),
 ('repair', 'traffic light'),
 ('stand under', 'traffic light'),
 ('stop at', 'traffic light'),
 ('no interaction', 'traffic light'),
 ('direct', 'truck'),
 ('drive', 'truck'),
 ('inspect', 'truck'),
 ('load', 'truck'),
 ('repair', 'truck'),
 ('ride', 'truck'),
 ('sit on', 'truck'),
 ('wash', 'truck'),
 ('no interaction', 'truck'),
 ('carry', 'umbrella'),
 ('hold', 'umbrella'),
 ('lose', 'umbrella'),
 ('open', 'umbrella'),
 ('repair', 'umbrella'),
 ('set', 'umbrella'),
 ('stand under', 'umbrella'),
 ('no interaction', 'umbrella'),
 ('hold', 'vase'),
 ('make', 'vase'),
 ('paint', 'vase'),
 ('no interaction', 'vase'),
 ('fill', 'wine glass'),
 ('hold', 'wine glass'),
 ('sip', 'wine glass'),
 ('toast', 'wine glass'),
 ('lick', 'wine glass'),
 ('wash', 'wine glass'),
 ('no interaction', 'wine glass'),
 ('feed', 'zebra'),
 ('hold', 'zebra'),
 ('pet', 'zebra'),
 ('watch', 'zebra'),
 ('no interaction', 'zebra')]

hico_verbs = ['adjust', 'assemble', 'block', 'blow', 'board', 'break', 'brush with', 'buy', 'carry', 'catch',
 'chase', 'check', 'clean', 'control', 'cook', 'cut', 'cut with', 'direct', 'drag', 'dribble',
 'drink with', 'drive', 'dry', 'eat', 'eat at', 'exit', 'feed', 'fill', 'flip', 'flush',
 'fly', 'greet', 'grind', 'groom', 'herd', 'hit', 'hold', 'hop on', 'hose', 'hug',
 'hunt', 'inspect', 'install', 'jump', 'kick', 'kiss', 'lasso', 'launch', 'lick', 'lie on', 
 'lift', 'light', 'load', 'lose', 'make', 'milk', 'move', 'no interaction', 'open', 'operate',
 'pack', 'paint', 'park', 'pay', 'peel', 'pet', 'pick', 'pick up', 'point', 'pour', 
 'pull', 'push', 'race', 'read', 'release', 'repair', 'ride', 'row', 'run', 'sail', 
 'scratch', 'serve', 'set', 'shear', 'sign', 'sip', 'sit at', 'sit on', 'slide', 'smell', 
 'spin', 'squeeze', 'stab', 'stand on', 'stand under', 'stick', 'stir', 'stop at', 'straddle', 'swing', 
 'tag', 'talk on', 'teach', 'text on', 'throw', 'tie', 'toast', 'train', 'turn', 'type on', 
 'walk', 'wash', 'watch', 'wave', 'wear', 'wield', 'zip']
 
hico_objects = ['person', 'bicycle', 'car', 'motorcycle', 'airplane', 'bus', 'train', 'truck', 'boat', 'traffic_light', 
'fire_hydrant', 'stop_sign', 'parking_meter', 'bench', 'bird', 'cat', 'dog', 'horse', 'sheep', 'cow', 'elephant', 'bear', 
'zebra', 'giraffe', 'backpack', 'umbrella', 'handbag', 'tie', 'suitcase', 'frisbee', 'skis', 'snowboard', 'sports_ball', 
'kite', 'baseball_bat', 'baseball_glove', 'skateboard', 'surfboard', 'tennis_racket', 'bottle', 'wine_glass', 'cup', 'fork',
'knife', 'spoon', 'bowl', 'banana', 'apple', 'sandwich', 'orange', 'broccoli', 'carrot', 'hot_dog', 'pizza', 'donut', 'cake', 
'chair', 'couch', 'potted_plant', 'bed', 'dining_table', 'toilet', 'tv', 'laptop', 'mouse', 'remote', 'keyboard', 'cell_phone',
'microwave', 'oven', 'toaster', 'sink', 'refrigerator', 'book', 'clock', 'vase', 'scissors', 'teddy_bear', 'hair_drier', 'toothbrush']

hico_verbs_sentence = ['a photo of a person adjusting the object',
 'a photo of a person assembling the object',
 'a photo of a person blocking the object',
 'a photo of a person blowing the object',
 'a photo of a person boarding the object',
 'a photo of a person breaking the object',
 'a photo of a person brushing with the object',
 'a photo of a person buying the object',
 'a photo of a person carrying the object',
 'a photo of a person catching the object',
 'a photo of a person chasing the object',
 'a photo of a person checking the object',
 'a photo of a person cleaning the object',
 'a photo of a person controling the object',
 'a photo of a person cooking the object',
 'a photo of a person cutting the object',
 'a photo of a person cutting with the object',
 'a photo of a person directing the object',
 'a photo of a person draging the object',
 'a photo of a person dribbling the object',
 'a photo of a person drinking with the object',
 'a photo of a person driving the object',
 'a photo of a person drying the object',
 'a photo of a person eating the object',
 'a photo of a person eating at the object',
 'a photo of a person exiting the object',
 'a photo of a person feeding the object',
 'a photo of a person filling the object',
 'a photo of a person flipping the object',
 'a photo of a person flushing the object',
 'a photo of a person flying the object',
 'a photo of a person greeting the object',
 'a photo of a person grinding the object',
 'a photo of a person grooming the object',
 'a photo of a person herding the object',
 'a photo of a person hiting the object',
 'a photo of a person holding the object',
 'a photo of a person hopping on the object',
 'a photo of a person hosing the object',
 'a photo of a person hugging the object',
 'a photo of a person hunting the object',
 'a photo of a person inspecting the object',
 'a photo of a person installing the object',
 'a photo of a person jumping the object',
 'a photo of a person kicking the object',
 'a photo of a person kissing the object',
 'a photo of a person lassoing the object',
 'a photo of a person launching the object',
 'a photo of a person licking the object',
 'a photo of a person lying on the object',
 'a photo of a person lifting the object',
 'a photo of a person lighting the object',
 'a photo of a person loading the object',
 'a photo of a person losing the object',
 'a photo of a person making the object',
 'a photo of a person milking the object',
 'a photo of a person moving the object',
 'a photo of a person and the object with no interaction',
 'a photo of a person opening the object',
 'a photo of a person operating the object',
 'a photo of a person packing the object',
 'a photo of a person painting the object',
 'a photo of a person parking the object',
 'a photo of a person paying the object',
 'a photo of a person peeling the object',
 'a photo of a person petting the object',
 'a photo of a person picking the object',
 'a photo of a person picking up the object',
 'a photo of a person pointing the object',
 'a photo of a person pouring the object',
 'a photo of a person pulling the object',
 'a photo of a person pushing the object',
 'a photo of a person racing the object',
 'a photo of a person reading the object',
 'a photo of a person releasing the object',
 'a photo of a person repairing the object',
 'a photo of a person riding the object',
 'a photo of a person rowing the object',
 'a photo of a person running the object',
 'a photo of a person sailing the object',
 'a photo of a person scratching the object',
 'a photo of a person serving the object',
 'a photo of a person setting the object',
 'a photo of a person shearing the object',
 'a photo of a person signing the object',
 'a photo of a person siping the object',
 'a photo of a person sitting at the object',
 'a photo of a person sitting on the object',
 'a photo of a person sliding the object',
 'a photo of a person smelling the object',
 'a photo of a person spining the object',
 'a photo of a person squeezing the object',
 'a photo of a person stabbing the object',
 'a photo of a person standing on the object',
 'a photo of a person standing under the object',
 'a photo of a person sticking the object',
 'a photo of a person stirring the object',
 'a photo of a person stopping at the object',
 'a photo of a person straddling the object',
 'a photo of a person swinging the object',
 'a photo of a person tagging the object',
 'a photo of a person talking on the object',
 'a photo of a person teaching the object',
 'a photo of a person texting on the object',
 'a photo of a person throwing the object',
 'a photo of a person tying the object',
 'a photo of a person toasting the object',
 'a photo of a person training the object',
 'a photo of a person turning the object',
 'a photo of a person typing on the object',
 'a photo of a person walking the object',
 'a photo of a person washing the object',
 'a photo of a person watching the object',
 'a photo of a person waving the object',
 'a photo of a person wearing the object',
 'a photo of a person wielding the object',
 'a photo of a person zipping the object']

hico_verbs_sentence_noprefix = ['a person adjusting the object', 
'a person assembling the object', 
'a person blocking the object', 
'a person blowing the object', 
'a person boarding the object', 
'a person breaking the object', 
'a person brushing with the object', 
'a person buying the object', 
'a person carrying the object', 
'a person catching the object', 
'a person chasing the object', 
'a person checking the object', 
'a person cleaning the object', 
'a person controling the object', 
'a person cooking the object', 
'a person cutting the object', 
'a person cutting with the object', 
'a person directing the object', 
'a person draging the object', 
'a person dribbling the object',
'a person drinking with the object', 
'a person driving the object', 
'a person drying the object', 
'a person eating the object', 
'a person eating at the object', 
'a person exiting the object', 
'a person feeding the object', 
'a person filling the object', 
'a person flipping the object', 
'a person flushing the object', 
'a person flying the object', 
'a person greeting the object', 
'a person grinding the object', 
'a person grooming the object', 
'a person herding the object', 
'a person hiting the object', 
'a person holding the object', 
'a person hopping on the object', 
'a person hosing the object', 
'a person hugging the object', 
'a person hunting the object', 
'a person inspecting the object', 
'a person installing the object', 
'a person jumping the object', 
'a person kicking the object', 
'a person kissing the object', 
'a person lassoing the object', 
'a person launching the object', 
'a person licking the object', 
'a person lying on the object', 
'a person lifting the object', 
'a person lighting the object', 
'a person loading the object', 
'a person losing the object', 
'a person making the object', 
'a person milking the object', 
'a person moving the object', 
'a person and the object with no interaction', 
'a person opening the object', 
'a person operating the object', 
'a person packing the object', 
'a person painting the object', 
'a person parking the object', 
'a person paying the object', 
'a person peeling the object', 
'a person petting the object', 
'a person picking the object', 
'a person picking up the object', 
'a person pointing the object', 
'a person pouring the object', 
'a person pulling the object', 
'a person pushing the object', 
'a person racing the object', 
'a person reading the object', 
'a person releasing the object', 
'a person repairing the object', 
'a person riding the object', 
'a person rowing the object', 
'a person running the object', 
'a person sailing the object', 
'a person scratching the object', 
'a person serving the object', 
'a person setting the object', 
'a person shearing the object', 
'a person signing the object', 
'a person siping the object', 
'a person sitting at the object', 
'a person sitting on the object', 
'a person sliding the object', 
'a person smelling the object', 
'a person spining the object', 
'a person squeezing the object', 
'a person stabbing the object', 
'a person standing on the object', 
'a person standing under the object', 
'a person sticking the object', 
'a person stirring the object', 
'a person stopping at the object', 
'a person straddling the object', 
'a person swinging the object', 
'a person tagging the object', 
'a person talking on the object', 
'a person teaching the object', 
'a person texting on the object', 
'a person throwing the object', 
'a person tying the object', 
'a person toasting the object', 
'a person training the object', 
'a person turning the object', 
'a person typing on the object', 
'a person walking the object', 
'a person washing the object', 
'a person watching the object', 
'a person waving the object', 
'a person wearing the object', 
'a person wielding the object', 
'a person zipping the object']

hico_verb_object_sentence = ['adjust object', 'assemble object', 'block object', 'blow object', 'board object', 
'break object', 'brush with object', 'buy object', 'carry object', 'catch object', 
'chase object', 'check object', 'clean object', 'control object', 'cook object', 
'cut object', 'cut with object', 'direct object', 'drag object', 'dribble object', 
'drink with object', 'drive object', 'dry object', 'eat object', 'eat at object', 
'exit object', 'feed object', 'fill object', 'flip object', 'flush object', 
'fly object', 'greet object', 'grind object', 'groom object', 'herd object', 
'hit object', 'hold object', 'hop on object', 'hose object', 'hug object', 
'hunt object', 'inspect object', 'install object', 'jump object', 'kick object', 
'kiss object', 'lasso object', 'launch object', 'lick object', 'lie on object', 
'lift object', 'light object', 'load object', 'lose object', 'make object', 
'milk object', 'move object', 'no interaction object', 'open object', 'operate object', 
'pack object', 'paint object', 'park object', 'pay object', 'peel object', 
'pet object', 'pick object', 'pick up object', 'point object', 'pour object', 
'pull object', 'push object', 'race object', 'read object', 'release object', 
'repair object', 'ride object', 'row object', 'run object', 'sail object', 
'scratch object', 'serve object', 'set object', 'shear object', 'sign object', 
'sip object', 'sit at object', 'sit on object', 'slide object', 'smell object', 
'spin object', 'squeeze object', 'stab object', 'stand on object', 'stand under object', 
'stick object', 'stir object', 'stop at object', 'straddle object', 'swing object', 
'tag object', 'talk on object', 'teach object', 'text on object', 'throw object', 
'tie object', 'toast object', 'train object', 'turn object', 'type on object', 
'walk object', 'wash object', 'watch object', 'wave object', 'wear object', 'wield object', 'zip object']

